//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Nullable<System.DateTime> Date_order { get; set; }
        public Nullable<bool> Type_puchase { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Amount { get; set; }
        public int Code_purchase { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Delivery Delivery { get; set; }
    }
}
