//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issuance
    {
        public int Code_issuance { get; set; }
        public System.DateTime Date_order { get; set; }
        public int Amount { get; set; }
        public int Code_book { get; set; }
        public int ClientID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Client Client { get; set; }
    }
}
